# Generated by Django 4.1.2 on 2022-10-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_review_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='modified',
        ),
    ]
