# Generated by Django 4.1.2 on 2022-10-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
