# Generated by Django 4.1.2 on 2022-10-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
